test: add initial unit tests for simple string calculator
 FAIL  src/simpleCalc.test.ts
  ● Test suite failed to run

    Cannot find module './simpleCalc' from 'src/simpleCalc.test.ts'

    However, Jest was able to find:
        './simpleCalc.test.ts'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].

    See https://jestjs.io/docs/configuration#modulefileextensions-arraystring

    > 1 | import { add } from "./simpleCalc";
        | ^
      2 |
      3 | describe("Simple String Calculator", () => {
      4 |   test("should pass if function returns 0 for an empty string", () => {

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/simpleCalc.test.ts:1:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.423 s
Ran all test suites related to changed files.